version: "3"
services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672
    networks: 
      btw:
        aliases: 
          - rabbitmq
networks: 
  btw:
    external: true